version: "3.9"
services:
  app:
    build: .
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    environment:
      - TZ=America/Los_Angeles
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./backend:/app/backend
    restart: unless-stopped